trigger: none
  
pool: Default

stages:
  - stage: Init
    displayName: Init ho raha hai




    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'InfraPipeline'
              backendAzureRmStorageAccountName: 'stg07'
              backendAzureRmContainerName: 'tt07'
              backendAzureRmKey: 'tt1.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'InfraPipeline'
  - stage: 
    displayName: Manual Validation k liye bheja hai
    jobs:
      - job: 
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'cloud.sanjaysingh@gmail.com'
              approvers: 'cloud.sanjaysingh@gmail.com'
              onTimeout: 'resume'

  - stage:
    jobs:
      - job: 
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'InfraPipeline'
              backendAzureRmStorageAccountName: 'stg07'
              backendAzureRmContainerName: 'tt07'
              backendAzureRmKey: 'tt1.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'InfraPipeline'