trigger: none
  
pool: Default

stages:
  - stage: Init
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'InfraPipeline'
              backendAzureRmStorageAccountName: 'stg07'
              backendAzureRmContainerName: 'tt07'
              backendAzureRmKey: 'tt1.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'InfraPipeline'
          # - task: ManualValidation@1
          #   inputs:
          #     notifyUsers: 'tushartripathi21@gmail.com'
          #     onTimeout: 'resume'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'InfraPipeline'